// 명령 이름 → allow-/deny- 권한 자동 생성(permissions/autogenerated/).
// 이름은 commands.rs 의 #[tauri::command] 함수명과 정확히 일치해야 한다.
const COMMANDS: &[&str] = &[
    "snapshot",
    "record",
    "set_occlusion",
    "analyze_regions",
    "analyze_frame_diffs",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
